---
title: "Data preparation from Survey Monkey"
author: "Lynn Pallemaerts"
date: "2025-01-07"
output:
  html_document: default
---

# Libraries

```{r}
library(devtools)
devtools::install_github("mattroumaya/surveymonkey")
library(tidyverse)
```

# Connect with Survey monkey

```{r}
m5_survey <- surveymonkey::browse_surveys(title = "Indentifying data sharing issues regarding camera trap data in Europe -- dummy version",
                                          oauth_token = sm_oauth_token)
survey_ID <- c(m5_survey$id)

# Get whole survey
survey <- surveymonkey::fetch_survey_obj(survey_ID,
                                         oauth_token = sm_oauth_token)
survey_df <- surveymonkey::parse_survey(survey,
                                        oauth_token = sm_oauth_token) %>%
  surveymonkey::strip_html()
```

# Get question list

```{r}
qs <- read_delim("./Input/question_list_dummy.csv",
                 delim = ";")
```

# Basic data exploration

```{r}
# Get number of total respondents
length(unique(survey_df$respondent_id))

# Get number of complete responses
resp <- survey_df %>%
  select(-survey_id, -collector_id, -date_created, -date_modified) %>%
  filter(response_status == "completed") %>%
  select(-response_status)
length(unique(resp$respondent_id))
```

# Make subset for each question

```{r}
for (i in 1:nrow(qs)) {
  name <- qs$code[i]
  question <- qs$question[i]
  assign(name, 
         survey_df %>%
           dplyr::select(respondent_id, contains(question)))
}
remove(i, name, question)
```

# Clean individual dataframes

## Q1

```{r}
Q1 <- q1 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  filter(!is.na(response)) %>%
  mutate(question = qs$question[qs$code == "q1"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question1.csv")
remove(q1)
```

## Q2

```{r}
# WATCH OUT FO OTHER PLEASE SPECIFY
Q2 <- q2 %>%
  mutate(question = qs$question[qs$code == "q2"]) %>%
  rename(response = qs$question[qs$code == "q2"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question2.csv")
remove(q2)
```

## Q3

```{r}
Q3 <- q3 %>%
  mutate(question = qs$question[qs$code == "q3"]) %>%
  rename(response = qs$question[qs$code == "q3"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question3.csv")
remove(q3)
```

## Q4

```{r}
# WATCH OUT FO OTHER PLEASE SPECIFY
Q4 <- q4 %>%
  mutate(question = qs$question[qs$code == "q4"]) %>%
  rename(response = qs$question[qs$code == "q4"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question4.csv")
remove(q4)
```

## Q5

```{r}
Q5 <- q5 %>%
  mutate(question = qs$question[qs$code == "q5"]) %>%
  rename(response = qs$question[qs$code == "q5"]) %>%
  filter(!is.na(response)) %>% # For the repsondents that did not mark administration in Q4
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question5.csv")
remove(q5)
```

## Q6

```{r}
# WATCH OUT FO OTHER PLEASE SPECIFY
Q6 <- q6 %>%
  mutate(question = qs$question[qs$code == "q6"]) %>%
  rename(response = qs$question[qs$code == "q6"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question6.csv")
remove(q6)
```

## Q7

```{r}
Q7 <- q7 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q7"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(topic = long_answer) %>%
  select(respondent_id, question, topic, response) %>%
  write_csv2("./Interim/dummy_question7.csv")
remove(q7)
```

## Q8

```{r}
Q8 <- q8 %>%
  mutate(question = qs$question[qs$code == "q8"]) %>%
  rename(response = qs$question[qs$code == "q8"]) %>%
  filter(!is.na(response))%>% # for those who didn't fill this in
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question8.csv")
remove(q8)
```

## Q9

```{r}
Q9 <- q9 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q9"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question9.csv")
remove(q9)
```

## Q10

```{r}
Q10 <- q10 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q10"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question10.csv")
remove(q10)
```

## Q11

```{r}
Q11 <- q11 %>%
  mutate(question = qs$question[qs$code == "q11"]) %>%
  rename(response = qs$question[qs$code == "q11"]) %>%
  filter(!is.na(response))%>% # for those who didn't fill this in
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question11.csv")
remove(q11)
```

## Q12

```{r}
Q12 <- q12 %>%
  mutate(question = qs$question[qs$code == "q12"]) %>%
  rename(response = qs$question[qs$code == "q12"]) %>%
  filter(!is.na(response))%>% # for those who didn't fill this in
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question12.csv")
remove(q12)
```

## Q13

```{r}
Q13 <- q13 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q13"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question13.csv")
remove(q13)
```

## Q14

```{r}
Q14 <- q14 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q14"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question14.csv")
remove(q14)
```

## Q15

```{r}
Q15 <- q15 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q15"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question15.csv")
remove(q15)
```

## Q16

```{r}
Q16 <- q16 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q16"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question16.csv")
remove(q16)
```

## Q17

```{r}
Q17 <- q17 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q17"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question17.csv")
remove(q17)
```

## Q18

```{r}
Q18 <- q18 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q18"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question18.csv")
remove(q18)
```

## Q19

```{r}
Q19 <- q19 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q19"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question19.csv")
remove(q19)
```

## Q20

```{r}
Q20 <- q20 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q20"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question20.csv")
remove(q20)
```

## Q21

```{r}
Q21 <- q21 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q21"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question21.csv")
remove(q21)
```

## Q22

```{r}
Q22 <- q22 %>%
  pivot_longer(!respondent_id, names_to = "long_answer", values_to = "response") %>%
  mutate(question = qs$question[qs$code == "q22"]) %>%
  mutate(nchar = nchar(question)) %>%
  mutate(long_answer = substring(long_answer, nchar + 4)) %>%
  rename(charachteristic = long_answer) %>%
  select(respondent_id, question, charachteristic, response) %>%
  write_csv2("./Interim/dummy_question22.csv")
remove(q22)
```

## Q23

```{r}
Q23 <- q23 %>%
  mutate(question = qs$question[qs$code == "q23"]) %>%
  rename(response = qs$question[qs$code == "q23"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question23.csv")
remove(q23)
```

## Q24

```{r}
Q24 <- q24 %>%
  mutate(question = qs$question[qs$code == "q24"]) %>%
  rename(response = qs$question[qs$code == "q24"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question24.csv")
remove(q24)
```

## Q25

```{r}
Q25 <- q25 %>%
  mutate(question = qs$question[qs$code == "q25"]) %>%
  rename(response = qs$question[qs$code == "q25"]) %>%
  select(respondent_id, question, response) %>%
  write_csv2("./Interim/dummy_question25.csv")
remove(q25)
```

## Q26-29

```{r}
Q26789 <- q26 %>%
  left_join(q27, by = "respondent_id") %>%
    left_join(q28, by = "respondent_id") %>%
  left_join(q29, by = "respondent_id") %>%
  rename(gender = qs$question[qs$code == "q26"],
         age = qs$question[qs$code == "q27"],
         degree = qs$question[qs$code == "q28"],
         employment = qs$question[qs$code == "q29"]) %>%
  write_csv2("./Interim/dummy_question26789.csv")
remove(q26, q27, q28, q29)
```

89